server:
  port: 8082
spring:
  application:
    name: "ms-reporte"
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: "local"
    include: null
entrypoint:
  sqs:
    region: "us-east-1"
    endpoint: "https://sqs.us-east-1.amazonaws.com/057914081242/reportes"
    queueUrl: "https://sqs.us-east-1.amazonaws.com/057914081242/reportes"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  region: us-east-1
  dynamodb:
    endpoint: "https://dynamodb.us-east-1.amazonaws.com"
